#!/usr/bin/env bash

FROM mysql

ENV MYSQL_DATABASE 'demo2'
ENV MYSQL_USER 'demo2'
ENV MYSQL_PASSWORD 'B*T_ity6'
ENV MYSQL_ROOT_PASSWORD 'B*T_ity6'

EXPOSE 3306

VOLUME "/home/mirjalalcloud/db" "/var/lib/mysql"
